
CREATE TABLE DOCUMENT (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	pages int not null,
	last_modified timestamp default now()
);

insert into DOCUMENT (name, pages) values ('Document_test_1', 20);
insert into DOCUMENT (name, pages) values ('Document_test_2', 4);
insert into DOCUMENT (name, pages) values ('Document_test_3', 7);
insert into DOCUMENT (name, pages) values ('Document_test_4', 267);
insert into DOCUMENT (name, pages) values ('Document_test_5', 5);
insert into DOCUMENT (name, pages) values ('Document_test_6', 1);
insert into DOCUMENT (name, pages) values ('Document_test_7', 23);
insert into DOCUMENT (name, pages) values ('Document_test_8', 435);
insert into DOCUMENT (name, pages) values ('Document_test_9', 20);
insert into DOCUMENT (name, pages) values ('Document_test_10', 65);
insert into DOCUMENT (name, pages) values ('Document_test_11', 8);
insert into DOCUMENT (name, pages) values ('Document_test_12', 1);
insert into DOCUMENT (name, pages) values ('Document_test_13', 435);
insert into DOCUMENT (name, pages) values ('Document_test_14', 45);
insert into DOCUMENT (name, pages) values ('Document_test_15', 76);
insert into DOCUMENT (name, pages) values ('Document_test_16', 93);
insert into DOCUMENT (name, pages) values ('Document_test_17', 12);
insert into DOCUMENT (name, pages) values ('Document_test_18', 4);
insert into DOCUMENT (name, pages) values ('Document_test_19', 65);
insert into DOCUMENT (name, pages) values ('Document_test_20', 87);
insert into DOCUMENT (name, pages) values ('Document_test_21', 7);
insert into DOCUMENT (name, pages) values ('Document_test_22', 20);
insert into DOCUMENT (name, pages) values ('Document_test_23', 56);
insert into DOCUMENT (name, pages) values ('Document_test_24', 90);
insert into DOCUMENT (name, pages) values ('Document_test_25', 99);
insert into DOCUMENT (name, pages) values ('Document_test_26', 352);
insert into DOCUMENT (name, pages) values ('Document_test_27', 653);
insert into DOCUMENT (name, pages) values ('Document_test_28', 555);
insert into DOCUMENT (name, pages) values ('Document_test_29', 61);
insert into DOCUMENT (name, pages) values ('Document_test_30', 24);

